version: '3' #docker-compose version
services:
  my-app:
    image: 903716684127.dkr.ecr.us-east-2.amazonaws.com/my-app:1.2
    ports:
      - 3000:3000 
  mongodb: #container name
    image: mongo
    ports:
      - 27017:27017 #host:container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express: #container name
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local      